language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Q4VXhyWm+2JDDSnb++CNT/6zYJ4bQBM+cd1H8BwC6gfF8ljDwYnxwQ1NogDNOw3R7lE87EuWoyA5+8rqb8+sjWHEx94utN/sas+66w8V/9+LhE+CgyKybqUa5AaXlCrHQ73a2RgJ2bqjpN0FFCq8JnGshZv3NZx0Tv2vvb2ajqt1yTGovUuKQsD+lUdjzFp4hUZ9Nh+5qJDTM5G7Efiptxro5Cl5cc3z451FyO5z9rxLw2tVkBobQ1oSpcieR182PVAx/8bUTL5NDbjzetbEcjd6zFpoutjsFfX0cF8Y8hVeHlxbaxKoje+9f8atkw44u9BQenD+xW1SoB2Mfopcs8jUl7JpbUtEPqYJh+48JzD21TAdkWSAiX5BYl/KKFI6pyJqmvLY84BZf3u1371DtaS0QyBEIXvgG2bGqF4n48lNLR2E5x4JT7r/Uzi29du+EZ523uQYwWyhfbee+AGrDr1Up8MtEo1DmdOfv4E3RaPWkKbzQgpQyrZbBWAw+8OewpwteK5EH3LaHNUBIVQohrDGUdU+kzE3EPwfohZizvFHeME6Nv5Q0IvlSqvQCg9xOtyAqlUcsRzrbMf84nV/OlB1qGLkIsFZSz17G/YneL4DbE5da5dAuXbmTA/MPkiSTrr1iRkk9HRqEf58ENujg2JuGHBiguePdYvdZ5uXSIg=
  app: addressbook
  on:
    repo: technoligest/yaseraddressbook
